# Generated by Django 2.2.4 on 2019-10-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='leaf_image')),
            ],
        ),
    ]
