# Generated by Django 2.2.4 on 2019-12-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classify', '0002_testimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cause', models.CharField(max_length=100)),
                ('chemical', models.CharField(max_length=250)),
                ('suggestion', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Fruits',
        ),
    ]
